version: "3.2"
services:
  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      - AUTO_CREATE_TOPICS=true
      - ADVERTISED_HOST=localhost
      - ADVERTISED_PORT=9092
    restart: on-failure