kstreams:
    kafkaTopic: topic
    resultStoreName: CRYPTO_STORE
    bootstrapServer: localhost:9092
    applicationId: kaffka-crypto-app
    clientId: kaffka-crypto-client
    autoOffsetReset: earliest
    stateDir: /tmp/kafka-streams
    commitInterval: 100

sources:
    - name: kraken
      weight: 0.7
    - name: exmo
      weight: 1
    - name: binance
      weight: 0.4