logging.file: logs/spring-boot.log
kstreams:
    kafkaTopic: topic
    resultStoreName: CRYPTO_STORE
    bootstrapServer: localhost:9092
    applicationId: kaffka-crypto-app
    clientId: kaffka-crypto-client
    autoOffsetReset: earliest
    stateDir: /tmp/kafka-streams
    commitInterval: 100

sources:
    - name: binance
      weight: 1
    - name: exmo
      weight: 0.7
    - name: livecoin
      weight: 0.3
    - name: yobit
      weight: 1.1
    - name: hitbtc
      weight: 0.9
    - name: poloniex
      weight: 0.65
    - name: kraken
      weight: 0.8